# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7677bf34c0dfe75e2efc7ade6f1064b1aad7f97285dee174bfa67b8dfcd52d61ff5a1cd224834ede5e43099f05701efb07e02b98c8634d58408dabb69228c6d2

test:
  secret_key_base: 635918da7e4c55d2538292eb71d9d66504206f51823179c37a3279d12a1172de110639e86d418c2b109a9a1708f1d1fa1b83c0eddcfdcd71caf3e4057cf540a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
